package main

// Gods is an exported type that
// contains a structure for each
// smite god
type Gods struct {
	Name       string
	Pantheon   string
	Attack     string
	Power      string
	Class      string
	Difficulty string
}

var (
	GODS []*Gods
)

func init() {
	GODS = []*Gods{
		&Gods{
			Name:       "Agni",
			Pantheon:   "Hindu",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Ah Muzen Cab",
			Pantheon:   "Mayan",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Ah Puch",
			Pantheon:   "Mayan",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Amaterasu",
			Pantheon:   "Japanese",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Anhur",
			Pantheon:   "Egyptian",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Anubis",
			Pantheon:   "Egyptian",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Ao Kuang",
			Pantheon:   "Chinese",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Aphrodite",
			Pantheon:   "Greek",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Apollo",
			Pantheon:   "Greek",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Arachne",
			Pantheon:   "Greek",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Ares",
			Pantheon:   "Greek",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Artemis",
			Pantheon:   "Greek",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Athena",
			Pantheon:   "Greek",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Awilix",
			Pantheon:   "Mayan",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Bacchus",
			Pantheon:   "Roman",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Bakasura",
			Pantheon:   "Hindu",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Bastet",
			Pantheon:   "Egyptian",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Bellona",
			Pantheon:   "Roman",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Cabrakan",
			Pantheon:   "Mayan",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Camazotz",
			Pantheon:   "Mayan",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Chaac",
			Pantheon:   "Mayan",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Chang'e",
			Pantheon:   "Chinese",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Chiron",
			Pantheon:   "Greek",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Chronos",
			Pantheon:   "Greek",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Cupid",
			Pantheon:   "Roman",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Erlang Shen",
			Pantheon:   "Chinese",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Fafnir",
			Pantheon:   "Norse",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Fenrir",
			Pantheon:   "Norse",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Freya",
			Pantheon:   "Norse",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Geb",
			Pantheon:   "Egyptian",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Guan Yu",
			Pantheon:   "Chinese",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Hades",
			Pantheon:   "Greek",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "He Bo",
			Pantheon:   "Chinese",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Hel",
			Pantheon:   "Norse",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Hercules",
			Pantheon:   "Roman",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Hou Yi",
			Pantheon:   "Chinese",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Hun Batz",
			Pantheon:   "Mayan",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Isis",
			Pantheon:   "Egyptian",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Izanami",
			Pantheon:   "Japanese",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Janus",
			Pantheon:   "Roman",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Jing Wei",
			Pantheon:   "Chinese",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Kali",
			Pantheon:   "Hindu",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Khepri",
			Pantheon:   "Egyptian",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Kukulkan",
			Pantheon:   "Mayan",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Kumbhakarna",
			Pantheon:   "Hindu",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Loki",
			Pantheon:   "Norse",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Medusa",
			Pantheon:   "Greek",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Mercury",
			Pantheon:   "Roman",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Ne Zha",
			Pantheon:   "Chinese",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Neith",
			Pantheon:   "Egyptian",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Nemesis",
			Pantheon:   "Greek",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Nox",
			Pantheon:   "Roman",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Nu Wa",
			Pantheon:   "Chinese",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Odin",
			Pantheon:   "Norse",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Osiris",
			Pantheon:   "Egyptian",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Poseidon",
			Pantheon:   "Greek",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Ra",
			Pantheon:   "Egyptian",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Raijin",
			Pantheon:   "Japanese",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Rama",
			Pantheon:   "Hindu",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Ratatoskr",
			Pantheon:   "Norse",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Ravana",
			Pantheon:   "Hindu",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Scylla",
			Pantheon:   "Greek",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Serqet",
			Pantheon:   "Egyptian",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Skadi",
			Pantheon:   "Norse",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Sobek",
			Pantheon:   "Egyptian",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Sol",
			Pantheon:   "Norse",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Sun Wukong",
			Pantheon:   "Chinese",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Susano",
			Pantheon:   "Japanese",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Sylvanus",
			Pantheon:   "Roman",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Terra",
			Pantheon:   "Roman",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Thanatos",
			Pantheon:   "Greek",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Thor",
			Pantheon:   "Norse",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Assassin",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Tyr",
			Pantheon:   "Norse",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Ullr",
			Pantheon:   "Norse",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Hard",
		},
		&Gods{
			Name:       "Vamana",
			Pantheon:   "Hindu",
			Attack:     "Melee",
			Power:      "Physical",
			Class:      "Warrior",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Vulcan",
			Pantheon:   "Roman",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Xbalanque",
			Pantheon:   "Mayan",
			Attack:     "Ranged",
			Power:      "Physical",
			Class:      "Hunter",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Xing Tian",
			Pantheon:   "Chinese",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Ymir",
			Pantheon:   "Norse",
			Attack:     "Melee",
			Power:      "Magical",
			Class:      "Guardian",
			Difficulty: "Easy",
		},
		&Gods{
			Name:       "Zeus",
			Pantheon:   "Greek",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Average",
		},
		&Gods{
			Name:       "Zhong Kui",
			Pantheon:   "Chinese",
			Attack:     "Ranged",
			Power:      "Magical",
			Class:      "Mage",
			Difficulty: "Easy",
		},
	}
}
